#True,: thumbs up 
#False,: thumbs down
ratingsIndex = {"Canyon Vista": {
    'Assorted Summer Scones':True,
    'Beans' :True,
    'Blueberry Muffin':False,
    'Breakfast Streusel':True,
    'Cage Free Scrambled Eggs':False,
    'Carrots & Jalapenos':False,
    'Pork Sausage Links':False,
    'Whole Wheat English Muffin':False,
    'Chocolate Chip Pancakes':True,
    'Corned Beef Hash':False,
    'Fresh Tortillas':False,
    'Gluten Friendly Bread':True,
    'Hash Brown Potatoes':False,
    'Zucchini Breakfast Muffins':False,
    'Scrambled Egg Whites':False,
    'Smoked Bacon':True,
    'Steelcut Oatmeal':True,
    'Veggie Sausage':False,
    'Waffle':True,
    'Cereal with Milk':False,
    'Cut Fresh Fruit':True,
    'Whole Apple':True,
    'Whole Banana':False,
    'Whole Orange':False,
    'Yogurt Bar':False,
    'Seafood Veracruz':False,
    'Beef and Broccoli':True,
    'Lo Mein Noodle':False,
    'Stir Fried Rice':True,
    'Stir Fry Veg Mix':True,
    'Tuna Super Sub':False,
    'Turkey & Swiss Super Sub':False,
    'Vegetarian Super Wrap':False,
    'Cheeseburger':False,
    'Fish Sandwich':False,
    'Gardein Burger':False,
    'Hamburger':True,
    'Hot Dog':True,
    'Crispy French Fries':False,
    'Cheese Pizza':True,
    'Hawaiian Pizza':True,
    'Pepperoni Pizza':True,
    'BYO Pasta Bar (Alfredo Nutritional Sample)':True,
    'Garlic Bread':True,
    'Jalapeno Cornbread':True,
    'Corn Chowder Soup':False,
    'Vegetarian Chili':False,
    'Carrot Cake':False,
    'Chocolate Pudding':False,
    'Lemon Jello with Mandarin Oranges':True,
    'Rice Krispy Treats':False,
    'Curried Salmon':False,
    'Carved Roast Turkey':True,
    'Cajun Dirty  Rice':True,
    'Roasted Red Potatoes':False,
    'Steamed Vegetable Mix':True,
    'Cheese Pizza':False,
    'Hawaiian Pizza':False,
    'Pepperoni Pizza':False,
    'BYO Pasta Bar (Alfredo Nutritional Sample)':True,
    'Garlic Bread':True,
    'Jalapeno Cornbread':False,
    'Corn Chowder Soup':False,
    'Vegetarian Chili':False,
    'Carrot Cake':True,
    'Chocolate Pudding':True,
    'Lemon Jello with Mandarin Oranges':False,
    'Rice Krispy Treats':True,

    }, "Cafe Ventana": {


        }, "64 Degrees":{


            }
           }
